version: '3'
services:
  node:
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/src/app
    command: sh -c "cd app && npm run sass:compile && npm run start"
    ports:
      - 3000:3000